# Generated by Django 5.2.6 on 2025-10-21 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='label',
        ),
        migrations.AddField(
            model_name='events',
            name='label',
            field=models.CharField(choices=[('nuevo', 'Nuevo'), ('preventa', 'Preventa'), ('ninguno', 'Ninguno')], default='ninguno', max_length=20),
        ),
    ]
