# Generated by Django 5.2.6 on 2025-10-22 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_location_label_events_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.municipality'),
        ),
        migrations.AlterField(
            model_name='events',
            name='label',
            field=models.CharField(choices=[('proximamente', 'Próximamente'), ('preventa', 'Preventa'), ('ninguno', 'Ninguno')], default='ninguno', max_length=20),
        ),
    ]
