# Generated by Django 5.2.6 on 2025-10-21 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_artist_department_location_musicalgender_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='municipality',
        ),
    ]
