# Generated by Django 5.2.7 on 2025-10-22 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_events_place_alter_events_label'),
        ('core', '0003_remove_events_municipality'),
    ]

    operations = [
    ]
