# Generated by Django 5.2.7 on 2025-10-22 20:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_merge_20251022_1512'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='end_date',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='start_date',
            new_name='start',
        ),
        migrations.RemoveField(
            model_name='bought',
            name='status',
        ),
        migrations.RemoveField(
            model_name='bought',
            name='tickets',
        ),
        migrations.RemoveField(
            model_name='events',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='events',
            name='description',
        ),
        migrations.RemoveField(
            model_name='events',
            name='place',
        ),
        migrations.AddField(
            model_name='bought',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='bought',
            name='total_qty',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='events',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='events',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='label',
            field=models.CharField(choices=[('nuevo', 'Nuevo'), ('preventa', 'Preventa'), ('ninguno', 'Ninguno')], default='ninguno', max_length=20),
        ),
        migrations.AddField(
            model_name='tickets',
            name='bought',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='core.bought'),
        ),
        migrations.AddField(
            model_name='tickets',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='bought',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.profile'),
        ),
        migrations.AlterField(
            model_name='events',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.location'),
        ),
        migrations.AlterField(
            model_name='events',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='purchase_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='EventArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.artist')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.events')),
            ],
            options={
                'unique_together': {('artist', 'event')},
            },
        ),
        migrations.AddField(
            model_name='events',
            name='artists',
            field=models.ManyToManyField(related_name='events', through='core.EventArtist', to='core.artist'),
        ),
    ]
